/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/student": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List students in a class */
        get: operations["Students_list"];
        put?: never;
        /** @description Create a student */
        post: operations["Students_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/{studentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Students_getById"];
        /** @description Update a student */
        put: operations["Students_update"];
        post?: never;
        /** @description Delete a student */
        delete: operations["Students_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/year": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List years */
        get: operations["Years_list"];
        put?: never;
        /** @description Create a year */
        post: operations["Years_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/year/{yearId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Update a year */
        put: operations["Years_update"];
        post?: never;
        /** @description Delete a year */
        delete: operations["Years_delete"];
        options?: never;
        head?: never;
        /** @description Set active year */
        patch: operations["Years_setActive"];
        trace?: never;
    };
    "/year/{yearId}/class": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List classes in a year */
        get: operations["Classes_list"];
        put?: never;
        /** @description Create a class */
        post: operations["Classes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/year/{yearId}/class/{classId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Classes_getById"];
        /** @description Update a class */
        put: operations["Classes_update"];
        post?: never;
        /** @description Delete a class */
        delete: operations["Classes_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/year/{yearId}/class/{classId}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get check dates by class id */
        get: operations["Check_listByClassId"];
        put?: never;
        /** @description Create a check date */
        post: operations["Check_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/year/{yearId}/class/{classId}/check/{checkDateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Update a check date */
        put: operations["Check_update"];
        post?: never;
        /** @description Delete a check date */
        delete: operations["Check_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/year/{yearId}/class/{classId}/member": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Classes_getMembers"];
        put: operations["Classes_addOrRemoveMember"];
        post: operations["Classes_addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CheckDate: {
            id: string;
            classId: string;
            date: string;
            isEditable: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Class: {
            id: string;
            year: string;
            name: string;
            subject: string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ClassMemberDetail: {
            id: string;
            classId: string;
            studentId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            student: {
                id: string;
                teacher: string;
                code: string;
                prefix: string;
                firstName: string;
                lastName: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                nickname?: string;
            };
        };
        CreateCheckDateBody: {
            date: string;
        };
        CreateClassBody: {
            year: string;
            name: string;
            subject: string;
            isActive?: boolean;
        };
        CreateStudentBody: {
            prefix: string;
            code: string;
            firstName: string;
            lastName: string;
            nickname?: string;
        };
        CreateYearBody: {
            /** Format: int32 */
            year: number;
            /** Format: int32 */
            term: number;
            isActive?: boolean;
        };
        EmptyData: Record<string, never>;
        PatchClassMemberBody: {
            studentId?: string;
        };
        Student: {
            id: string;
            teacher: string;
            code: string;
            prefix: string;
            firstName: string;
            lastName: string;
            nickname?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateCheckDateBody: {
            date?: string;
            isEditable?: boolean;
        };
        UpdateClassBody: {
            year?: string;
            name?: string;
            subject?: string;
            isActive?: boolean;
            /** Format: date-time */
            updatedAt?: string;
        };
        UpdateStudentBody: {
            prefix?: string;
            code?: string;
            firstName?: string;
            lastName?: string;
            nickname?: string;
        };
        UpdateYearBody: {
            user?: string;
            /** Format: int32 */
            year?: number;
            /** Format: int32 */
            term?: number;
            isActive?: boolean;
            /** Format: date-time */
            updatedAt?: string;
        };
        Year: {
            id: string;
            user: string;
            /** Format: int32 */
            year: number;
            /** Format: int32 */
            term: number;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Students_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["Student"][];
                        error?: string;
                    };
                };
            };
        };
    };
    Students_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStudentBody"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["Student"];
                        error?: string;
                    };
                };
            };
        };
    };
    Students_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["Student"];
                        error?: string;
                    };
                };
            };
        };
    };
    Students_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStudentBody"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["Student"];
                        error?: string;
                    };
                };
            };
        };
    };
    Students_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["EmptyData"];
                        error?: string;
                    };
                };
            };
        };
    };
    Years_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["Year"][];
                        error?: string;
                    };
                };
            };
        };
    };
    Years_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateYearBody"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["Year"];
                        error?: string;
                    };
                };
            };
        };
    };
    Years_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                yearId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateYearBody"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["Year"];
                        error?: string;
                    };
                };
            };
        };
    };
    Years_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                yearId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["EmptyData"];
                        error?: string;
                    };
                };
            };
        };
    };
    Years_setActive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                yearId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["EmptyData"];
                        error?: string;
                    };
                };
            };
        };
    };
    Classes_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                yearId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["Class"][];
                        error?: string;
                    };
                };
            };
        };
    };
    Classes_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                yearId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClassBody"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["Class"];
                        error?: string;
                    };
                };
            };
        };
    };
    Classes_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                yearId: string;
                classId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["Class"];
                        error?: string;
                    };
                };
            };
        };
    };
    Classes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                yearId: string;
                classId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClassBody"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["Class"];
                        error?: string;
                    };
                };
            };
        };
    };
    Classes_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                yearId: string;
                classId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["EmptyData"];
                        error?: string;
                    };
                };
            };
        };
    };
    Check_listByClassId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                yearId: string;
                classId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["CheckDate"][];
                        error?: string;
                    };
                };
            };
        };
    };
    Check_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                yearId: string;
                classId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCheckDateBody"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["CheckDate"];
                        error?: string;
                    };
                };
            };
        };
    };
    Check_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                yearId: string;
                classId: string;
                checkDateId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCheckDateBody"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["CheckDate"];
                        error?: string;
                    };
                };
            };
        };
    };
    Check_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                yearId: string;
                classId: string;
                checkDateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["EmptyData"];
                        error?: string;
                    };
                };
            };
        };
    };
    Classes_getMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                yearId: string;
                classId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["ClassMemberDetail"][];
                        error?: string;
                    };
                };
            };
        };
    };
    Classes_addOrRemoveMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                yearId: string;
                classId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchClassMemberBody"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["EmptyData"];
                        error?: string;
                    };
                };
            };
        };
    };
    Classes_addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                yearId: string;
                classId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStudentBody"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data?: components["schemas"]["EmptyData"];
                        error?: string;
                    };
                };
            };
        };
    };
}
